### ISSUE TITLE
Compile error with multicore compile

### ISSUE THREAD

**Issue by z3ntu** [AyatanaIndicators/ayatana-indicator-messages#29] opened 2022-01-15 16:58 UTC
```
make[2]: *** No rule to make target 'src/indicator-messages-service.c', needed by 'tests/CMakeFiles/indicator-messages-service.dir/__/src/indicator-messages-service.c.o'.  Stop.
```
See build log https://gitlab.alpinelinux.org/z3ntu/aports/-/jobs/594755/raw or https://gitlab.alpinelinux.org/z3ntu/aports/-/jobs/594802/raw

Using `-j1` for make seems to work around this well.

**Comment by tari01** [comment] 2022-01-17 10:53
@z3ntu 

I cannot replicate this - I always do test builds with `-j 4` using both **clang** and **gcc**. Can you please give me the exact command line you use for `cmake ..` and `make`? Thanks.

**Comment by z3ntu** [comment] 2022-01-17 18:54
Here's the build script: https://gitlab.alpinelinux.org/alpine/aports/-/blob/7feec0019c7180eee572413171432418f358f740/testing/ayatana-indicator-messages/APKBUILD

I'm not really sure how many threads the build machine has though, but I assume more than 4.. Also didn't happen every time but often enough on the builders there to need the workaround.

**Comment by tari01** [comment] 2022-01-19 12:45
@z3ntu 

I've run a loop of 1000 builds with your parameters using `-j 8`, bull no error on my end. I need a little help from you - could you please try to replace this block in `tests/CMakeLists.txt`:

```
set_source_files_properties(${HEADERS_GEN} ${SOURCES_GEN} PROPERTIES GENERATED TRUE)
set_source_files_properties(${HEADERS} ${SOURCES} PROPERTIES COMPILE_FLAGS ${COMPILE_FLAGS})
add_library("indicator-messages-service" STATIC ${HEADERS} ${HEADERS_GEN} ${SOURCES} ${SOURCES_GEN})
target_include_directories("indicator-messages-service" PUBLIC ${PROJECT_DEPS_INCLUDE_DIRS})
target_compile_definitions("indicator-messages-service" PUBLIC G_LOG_DOMAIN="Ayatana-Indicator-Messages")
target_link_libraries("indicator-messages-service")
```
with:

```
set_source_files_properties(${HEADERS_GEN} ${SOURCES_GEN} PROPERTIES GENERATED TRUE)
set_source_files_properties(${HEADERS} ${SOURCES} PROPERTIES COMPILE_FLAGS ${COMPILE_FLAGS})
add_library("indicator-messages-service" STATIC ${HEADERS} ${HEADERS_GEN} ${SOURCES} ${SOURCES_GEN})
target_include_directories("indicator-messages-service" PUBLIC ${PROJECT_DEPS_INCLUDE_DIRS})
target_compile_definitions("indicator-messages-service" PUBLIC G_LOG_DOMAIN="Ayatana-Indicator-Messages")
add_dependencies("indicator-messages-service" "ayatana-indicator-messages-service")
```

(the change is the last line).

Let's see if the explicit dependency gets you the `indicator-messages-service` test library built...

**Comment by psycholance** [comment] 2022-02-05 12:05
appears to now be functional with that change (https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/30509/diffs?commit_id=3110ce590b56eff1ed0fcd54120f5ae33b047e16)

**Comment by z3ntu** [comment] 2022-02-05 12:14
Yep, wanted to comment that. Works now reliably where before it failed most of the time in Alpine CI (@psycholance do you know how many cores the x86/x86_64 CI machines have?)

**Comment by psycholance** [comment] 2022-02-05 12:21
CI is... either 48 or 64, forget which. similar for the actual builders

**Comment by psycholance** [comment] 2022-02-05 12:26
i can reproduce this consistently on one of the developer machines with 48 threads, and funnily, the problem is also fixed by using -G Ninja with cmake and using ninja/samurai as the build tool, without the above patch

**Comment by z3ntu** [comment] 2022-02-05 13:12
Sounds like CMake is flawless /s

And thanks for trying :)

**Closed** 2022-02-08 21:06 UTC
